"""
First-run setup wizard — lightweight Flask app that collects initial
configuration and writes the .env file so the main system can start.
"""

import json
import logging
import os
import threading
import time
from pathlib import Path

from flask import Flask, jsonify, render_template, request

from config.settings import get_env_file_path

logger = logging.getLogger(__name__)

# Minimal .env template used when .env.example is missing
_FALLBACK_TEMPLATE = """\
# Auto-generated by setup wizard
ENVIRONMENT=production
CONTENT_BASE_DIR={content_base_dir}

# OBS WebSocket Settings
OBS_HOST=localhost
OBS_PORT=4455
OBS_PASSWORD={obs_password}
OBS_TIMEOUT=10
OBS_STARTUP_DELAY=15

# WebDAV/Synology Settings
WEBDAV_HOST={webdav_host}
WEBDAV_PORT=5006
WEBDAV_USERNAME={webdav_username}
WEBDAV_PASSWORD={webdav_password}
WEBDAV_TIMEOUT=30
WEBDAV_SYNC_INTERVAL=30
WEBDAV_ROOT_PATH={webdav_root_path}

# Media Settings
VIDEO_WIDTH=1920
VIDEO_HEIGHT=1080
VIDEO_FPS=30
IMAGE_DISPLAY_TIME=15
MAX_VIDEO_DURATION=900
SLIDE_TRANSITION_SECONDS=15
TRANSITION_START_OFFSET=2.0

# Audio Settings
AUDIO_SAMPLE_RATE=48000
AUDIO_CHANNELS=2
AUDIO_BUFFER_SIZE=1024

# Scheduling
SCHEDULE_ENABLED=true
TIMEZONE={timezone}
SCHEDULE_CHECK_INTERVAL=60
MANUAL_CONTENT_FOLDER=

# Web UI
WEB_UI_ENABLED=true
WEB_UI_PORT=8080

# Logging
LOG_LEVEL=INFO
"""

# Fields the wizard controls, mapped to .env key prefixes
_WIZARD_FIELDS = {
    "obs_password": "OBS_PASSWORD",
    "webdav_host": "WEBDAV_HOST",
    "webdav_username": "WEBDAV_USERNAME",
    "webdav_password": "WEBDAV_PASSWORD",
    "webdav_root_path": "WEBDAV_ROOT_PATH",
    "timezone": "TIMEZONE",
}

# Password keys — inline comments stripped on these lines
_PASSWORD_KEYS = {"OBS_PASSWORD", "WEBDAV_PASSWORD"}


def create_setup_app() -> Flask:
    """Create the setup wizard Flask application."""
    app = Flask(
        __name__,
        template_folder=str(Path(__file__).parent / "templates"),
        static_folder=str(Path(__file__).parent / "static"),
    )

    env_path = get_env_file_path()

    @app.after_request
    def security_headers(response):
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'"
        )
        return response

    @app.route("/")
    def setup_page():
        return render_template("setup.html", already_configured=env_path.exists())

    @app.route("/api/setup/test-obs", methods=["POST"])
    def test_obs():
        data = request.get_json(silent=True)
        if not data:
            return jsonify({"ok": False, "error": "No data provided"}), 400

        password = data.get("password", "")
        host = data.get("host", "localhost")
        port = int(data.get("port", 4455))

        try:
            import obsws_python as obs
        except ImportError:
            return jsonify({"ok": False, "error": "obsws_python is not installed. Run: pip install obsws-python"})

        try:
            client = obs.ReqClient(host=host, port=port, password=password, timeout=5)
            version = client.get_version()
            client.base_client.ws.close()
            return jsonify({"ok": True, "obs_version": version.obs_version})
        except Exception as e:
            return jsonify({"ok": False, "error": str(e)})

    @app.route("/api/setup/test-webdav", methods=["POST"])
    def test_webdav():
        data = request.get_json(silent=True)
        if not data:
            return jsonify({"ok": False, "error": "No data provided"}), 400

        host = (data.get("host") or "").strip()
        if not host:
            return jsonify({"ok": False, "error": "WebDAV host URL is required"})

        username = data.get("username", "")
        password = data.get("password", "")

        try:
            from webdav4.client import Client
        except ImportError:
            return jsonify({"ok": False, "error": "webdav4 is not installed. Run: pip install webdav4"})

        try:
            client = Client(host, auth=(username, password), timeout=10)
            client.ls("/")
            return jsonify({"ok": True})
        except Exception as e:
            return jsonify({"ok": False, "error": str(e)})

    @app.route("/api/setup/browse-folders", methods=["POST"])
    def browse_folders():
        """Browse folders on NAS using ad-hoc WebDAV credentials (setup only)."""
        data = request.get_json(silent=True)
        if not data:
            return jsonify({"ok": False, "error": "No data provided"}), 400

        host = (data.get("host") or "").strip()
        username = data.get("username", "")
        password = data.get("password", "")
        path = data.get("path", "/")

        if not host:
            return jsonify({"ok": False, "error": "WebDAV host is required"})

        # Sanitize path
        if "\x00" in path or any(ord(c) < 32 for c in path):
            return jsonify({"ok": False, "error": "Invalid path"})
        import posixpath
        clean = posixpath.normpath(path)
        if ".." in clean.split("/"):
            return jsonify({"ok": False, "error": "Invalid path"})
        if not clean.startswith("/"):
            clean = "/" + clean

        try:
            from webdav4.client import Client
            client = Client(host, auth=(username, password), timeout=10)
            items = client.ls(clean)
            folders = []
            for item in items:
                if item.get("type") == "directory":
                    name = item.get("name", "").rstrip("/").split("/")[-1]
                    if name and name != ".":
                        rel = f"{clean.rstrip('/')}/{name}"
                        folders.append({"name": name, "path": rel})
            return jsonify({"ok": True, "folders": folders})
        except Exception as e:
            return jsonify({"ok": False, "error": str(e)})

    @app.route("/api/setup/save", methods=["POST"])
    def save_config():
        data = request.get_json(silent=True)
        if not data:
            return jsonify({"error": "No data provided"}), 400

        # Overwrite guard
        if env_path.exists():
            return jsonify({"error": "Configuration file already exists. Delete it manually to re-run setup."}), 409

        # Required field
        obs_password = (data.get("obs_password") or "").strip()
        if not obs_password:
            return jsonify({"error": "OBS Password is required"}), 400

        # Reject '#' in passwords (settings.py strips inline comments)
        webdav_password = (data.get("webdav_password") or "").strip()
        if "#" in obs_password:
            return jsonify({"error": "OBS Password cannot contain '#' (the config parser treats it as a comment)"}), 400
        if "#" in webdav_password:
            return jsonify({"error": "WebDAV Password cannot contain '#' (the config parser treats it as a comment)"}), 400

        # Timezone validation
        timezone = (data.get("timezone") or "UTC").strip()
        try:
            from zoneinfo import ZoneInfo
            ZoneInfo(timezone)
        except Exception:
            return jsonify({"error": f"Invalid timezone: '{timezone}'"}), 400

        webdav_host = (data.get("webdav_host") or "").strip()
        webdav_username = (data.get("webdav_username") or "").strip()
        webdav_root_path = (data.get("webdav_root_path") or "/").strip()
        default_folder = (data.get("default_folder") or "").strip()

        project_root = str(Path(__file__).parent.parent.parent)

        field_values = {
            "OBS_PASSWORD": obs_password,
            "WEBDAV_HOST": webdav_host,
            "WEBDAV_USERNAME": webdav_username,
            "WEBDAV_PASSWORD": webdav_password,
            "WEBDAV_ROOT_PATH": webdav_root_path,
            "TIMEZONE": timezone,
            "CONTENT_BASE_DIR": project_root,
        }

        try:
            config_content = _build_config(field_values, env_path)

            # Atomic write
            tmp_path = env_path.with_suffix(".tmp")
            env_path.parent.mkdir(parents=True, exist_ok=True)
            tmp_path.write_text(config_content)
            os.replace(str(tmp_path), str(env_path))

            # Write schedules.json with default folder matching WebDAV structure
            _write_initial_schedules(env_path.parent, webdav_root_path, default_folder)

            app.config["SETUP_COMPLETE"] = True
            return jsonify({"ok": True})

        except Exception as e:
            return jsonify({"error": f"Failed to write config: {e}"}), 500

    return app


def _write_initial_schedules(config_dir: Path, webdav_root_path: str, default_folder: str) -> None:
    """Write initial schedules.json so the default folder matches WebDAV layout."""
    schedules_path = config_dir / "schedules.json"
    if schedules_path.exists():
        return  # Don't overwrite existing schedules

    # Build the folder path the content manager will use.
    # WebDAV syncs into <root_folder_name>/ locally, and the schedule folder
    # is relative to that, e.g. "default_slideshow" inside the root.
    root_name = webdav_root_path.strip("/").split("/")[0] if webdav_root_path.strip("/") else ""
    if default_folder:
        # default_folder is the subfolder name from the NAS
        folder = f"{root_name}/{default_folder}" if root_name else default_folder
    elif root_name:
        folder = root_name
    else:
        folder = "content/default"

    data = {
        "default_schedule": {
            "folder": folder,
            "transition": "Fade",
            "transition_offset": 0.5,
            "image_display_time": 15,
            "audio_volume": 80,
        },
        "schedules": [],
    }
    tmp = schedules_path.with_suffix(".json.tmp")
    config_dir.mkdir(parents=True, exist_ok=True)
    with open(tmp, "w") as f:
        json.dump(data, f, indent=2)
    os.replace(str(tmp), str(schedules_path))
    logger.info(f"Created schedules.json with default folder: {folder}")


def _build_config(field_values: dict, env_path: Path) -> str:
    """Build config file content from template + wizard values."""
    # Try to use .env.example as template
    example_path = env_path.with_suffix(".env.example")
    if not example_path.exists():
        # Try alternate naming: <name>.example
        example_path = env_path.parent / (env_path.name + ".example")

    if example_path.exists():
        return _apply_to_template(example_path, field_values)

    # Fallback: generate from hardcoded template
    return _FALLBACK_TEMPLATE.format(
        content_base_dir=field_values.get("CONTENT_BASE_DIR", ""),
        obs_password=field_values.get("OBS_PASSWORD", ""),
        webdav_host=field_values.get("WEBDAV_HOST", ""),
        webdav_username=field_values.get("WEBDAV_USERNAME", ""),
        webdav_password=field_values.get("WEBDAV_PASSWORD", ""),
        webdav_root_path=field_values.get("WEBDAV_ROOT_PATH", "/"),
        timezone=field_values.get("TIMEZONE", "UTC"),
    )


def _apply_to_template(example_path: Path, field_values: dict) -> str:
    """Read .env.example and replace wizard-controlled fields."""
    lines = []
    for line in example_path.read_text().splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in field_values:
                new_value = field_values[key]
                # For password lines, don't include any inline comment
                if key in _PASSWORD_KEYS:
                    lines.append(f"{key}={new_value}")
                else:
                    # Preserve inline comment from template if present
                    original_value_part = stripped.split("=", 1)[1]
                    comment = ""
                    if "#" in original_value_part:
                        idx = original_value_part.index("#")
                        comment = "  " + original_value_part[idx:].strip()
                    if comment:
                        lines.append(f"{key}={new_value}{comment}")
                    else:
                        lines.append(f"{key}={new_value}")
                continue
        lines.append(line)
    return "\n".join(lines) + "\n"


def run_setup_wizard(port: int = 8080) -> None:
    """Run the setup wizard server, blocking until config is saved or Ctrl+C."""
    app = create_setup_app()

    # Suppress Flask/Werkzeug default logging
    log = logging.getLogger("werkzeug")
    log.setLevel(logging.WARNING)

    try:
        from werkzeug.serving import make_server
        server = make_server("0.0.0.0", port, app)
    except OSError as e:
        print(f"\n  Error: Cannot start setup wizard on port {port}: {e}")
        print(f"  Make sure port {port} is not in use by another application.")
        import sys
        sys.exit(1)

    print(f"  Open your browser to http://localhost:{port}")
    print("  Press Ctrl+C to cancel.\n")

    def shutdown_poller():
        """Poll for SETUP_COMPLETE flag, then shut down the server."""
        while not app.config.get("SETUP_COMPLETE"):
            time.sleep(0.5)
        # Give the HTTP response time to reach the browser
        time.sleep(1)
        server.shutdown()

    poller = threading.Thread(target=shutdown_poller, daemon=True)
    poller.start()

    server.serve_forever()
